playlists:
    Top 50 - Global: '37i9dQZEVXbMDoHDwVN2tF'
    Top 50 - USA: '37i9dQZEVXbLRQDuF5jeBp'
    Top 50 - Canada: '37i9dQZEVXbKj23U1GF4IR'
    Top 50 - Brazil: '37i9dQZEVXbMXbN3EUUhlg'
    Top 50 - Argentina: '37i9dQZEVXbMMy2roB9myp'
    Top 50 - Germany: '37i9dQZEVXbJiZcmkrIHGU'
    Top 50 - France: '37i9dQZEVXbIPWwFssbupI'
    Top 50 - Spain: '37i9dQZEVXbNFJfN1Vw8d9'
    Top 50 - Ukraine: '37i9dQZEVXbKkidEfWYRuD'
    Top 50 - South Africa: '37i9dQZEVXbMH2jvi6jvjk'
    Top 50 - Egypt: '37i9dQZEVXbLn7RQmT5Xv2'
    Top 50 - UAE: '37i9dQZEVXbM4UZuIrvHvA'
    Top 50 - Saudi Arabia: '37i9dQZEVXbLrQBcXqUtaC'
    Top 50 - Japan: '37i9dQZEVXbKXQ4mDTEBXq'
    Top 50 - South Korea: '37i9dQZEVXbNxXF4SkHj9F'
    Top 50 - India: '37i9dQZEVXbLZ52XmnySJg'
    Top 50 - United Kingdom: '37i9dQZEVXbLnolsZ8PSNw'
    Top 50 - Nigeria: '37i9dQZEVXbKY7jLzlJ11V'
