data_dir:
  - './data/preprocessed/'

raw_dir:
  - './data/raw/playlists/'

files_names:
  - 'albums.csv'
  - 'artists.csv'
  - 'artists_genres_discogs.csv'
  - 'artists_genres_full.csv'
  - 'playlists.csv'
  - 'tracks.csv'
  - 'tracks_audio_features.csv'
  - 'tracks_genres_discogs.csv'
  - 'tracks_genres_theaudiodb.csv'